project:
  type: website

website:
  title: "AP Exam Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - model.qmd
      - sources.qmd
      - href: about.qmd
        text: Author

format:
  html:
    theme: lux
    css: styles.css
    toc: true



